#!/usr/bin/python3
from time import time;
from array import array
import sys

t0 = time()
n = int(sys.argv[1]) if len(sys.argv) >= 2 else 1000000
notprime = array('B', b'\0' * (n + 1))
found = 0

for i in range(2, n + 1):
    if notprime[i]:
        continue

    # print("prime:", i)
    found += 1

    for j in range(2 * i, n + 1, i):
        notprime[j] = 1

t1 = time()
print(found, "primes <= ", n, "found in", t1 - t0, "seconds")

# vim: noexpandtab sw=4
