#!/usr/bin/python
n = 1000000
notprime = []
for i in range(0, n + 1):
    notprime.append(0)

for i in range(2, n):
    if notprime[i]:
        continue

    # print "prime:", i

    for j in range(2 * i, n + 1, i):
        notprime[j] = 1

# vim: noexpandtab sw=4
