#!/usr/bin/python
from time import time;
t0 = time()
n = 1000000
notprime = []
for i in range(0, n + 1):
    notprime.append(0)

for i in range(2, n):
    if notprime[i]:
        continue

    # print "prime:", i

    for j in range(2 * i, n + 1, i):
        notprime[j] = 1

t1 = time()
print(t1 - t0)
# vim: noexpandtab sw=4
